// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBelvJlItvwIT7DruoUJ7wp5SYmZ9hWYfI',
    appId: '1:469959485469:web:30e523161eab47cff7fef4',
    messagingSenderId: '469959485469',
    projectId: 'min-app-114c6',
    authDomain: 'min-app-114c6.firebaseapp.com',
    storageBucket: 'min-app-114c6.firebasestorage.app',
    measurementId: 'G-JPRYHD4RPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijQ05DekiB7q2w_xxvn4rxDdoW_hmB18',
    appId: '1:469959485469:android:eb51e85da0236a93f7fef4',
    messagingSenderId: '469959485469',
    projectId: 'min-app-114c6',
    storageBucket: 'min-app-114c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrAvKy_2drnxzVzZoqKaLm8R6IYGl4Fo',
    appId: '1:469959485469:ios:f028c87b0e206d6ff7fef4',
    messagingSenderId: '469959485469',
    projectId: 'min-app-114c6',
    storageBucket: 'min-app-114c6.firebasestorage.app',
    iosBundleId: 'com.example.notetakingMinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgrAvKy_2drnxzVzZoqKaLm8R6IYGl4Fo',
    appId: '1:469959485469:ios:f028c87b0e206d6ff7fef4',
    messagingSenderId: '469959485469',
    projectId: 'min-app-114c6',
    storageBucket: 'min-app-114c6.firebasestorage.app',
    iosBundleId: 'com.example.notetakingMinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBelvJlItvwIT7DruoUJ7wp5SYmZ9hWYfI',
    appId: '1:469959485469:web:b6eb725c43c791c7f7fef4',
    messagingSenderId: '469959485469',
    projectId: 'min-app-114c6',
    authDomain: 'min-app-114c6.firebaseapp.com',
    storageBucket: 'min-app-114c6.firebasestorage.app',
    measurementId: 'G-J9EB17QZ0H',
  );
}
